{
 "title": "Energieverbruik",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_CONSUMED",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_CONSUMED",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_CONSUMED",
     "legendFormat": "L3"
    }
   ]
  },
  {
   "title": "Waterverbruik",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(reading_watermeter_reading_current_value[2m])/1000",
     "legendFormat": "Waterverbruik"
    }
   ]
  },
  {
   "title": "AC Watts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_AC_Watts_W", "legendFormat": "AC Watts" }
   ]
  },
  {
   "title": "Inverter Temperatuur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_Inverter_Temperature_c" }
   ]
  },
  {
   "title": "-L1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_DELIVERED",
     "legendFormat": "-L1"
    }
   ]
  },
  {
   "title": "-L2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_DELIVERED",
     "legendFormat": "-L2"
    }
   ]
  },
  {
   "title": "-L3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_DELIVERED",
     "legendFormat": "-L3"
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "delta(reading_GAS_READING[1h])", "legendFormat": "Gasverbruik" }
   ]
  },
  {
   "title": "Meterstanden",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "reading_watermeter_reading_current_value/1000",
     "legendFormat": "Watermeter"
    },
    { "expr": "reading_GAS_READING", "legendFormat": "Gas" },
    { "expr": "reading_Generated_All_time", "legendFormat": "Solar" },
    {
     "expr": "reading_ELECTRICITY_DELIVERED_TO_CLIENT_LOW_TARIFF",
     "legendFormat": "Electra laag tarief"
    },
    {
     "expr": "reading_ELECTRICITY_DELIVERED_TO_CLIENT_NORMAL_TARIFF",
     "legendFormat": "Electra normaal tarief"
    }
   ]
  },
  {
   "title": "Stroom",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L1_CONSUMED",
     "legendFormat": "L1"
    },
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L2_CONSUMED",
     "legendFormat": "L2"
    },
    {
     "expr": "reading_INSTANTANEOUS_ACTIVE_POWER_L3_CONSUMED",
     "legendFormat": "L3"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L1_DELIVERED",
     "legendFormat": "-L1"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L2_DELIVERED",
     "legendFormat": "-L2"
    },
    {
     "expr": "-reading_INSTANTANEOUS_ACTIVE_POWER_L3_DELIVERED",
     "legendFormat": "-L3"
    }
   ]
  },
  {
   "title": "Temperatuur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_temp" }
   ]
  },
  {
   "title": "Wind snelheid",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_wind_speed" }
   ]
  },
  {
   "title": "Zonsopgang",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_sunrise" }
   ]
  },
  {
   "title": "Zonondergang",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_sunset" }
   ]
  },
  {
   "title": "Verbruik",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "delta(reading_watermeter_reading_current_value[2m])/1000",
     "legendFormat": "Watermeter"
    },
    { "expr": "delta(reading_GAS_READING[1h])", "legendFormat": "Gas" },
    {
     "expr": "delta(reading_Generated_All_time[1h])",
     "legendFormat": "Solar"
    },
    {
     "expr": "delta(reading_ELECTRICITY_DELIVERED_TO_CLIENT_LOW_TARIFF[1h])",
     "legendFormat": "Electra laag tarief"
    },
    {
     "expr": "delta(reading_ELECTRICITY_DELIVERED_TO_CLIENT_NORMAL_TARIFF[1h])",
     "legendFormat": "Electra normaal tarief"
    }
   ]
  },
  {
   "title": "Bewolkt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_clouds" }
   ]
  },
  {
   "title": "Zonnekracht",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_uvi" }
   ]
  },
  {
   "title": "Atmosfeer druk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_pressure" }
   ]
  },
  {
   "title": "Wind richting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reading_wind_direction_deg" }
   ]
  }
 ]
}