{
 "title": "Energie",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Stroom",
   "type": "gauge",
   "description": "Power actually consumed by all devices and appliances in household.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "+P1",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L1_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "+P2",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L2_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "+P3",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L3_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "-P1",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L1_DELIVERED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "-P2",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L2_DELIVERED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "-P3",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L3_DELIVERED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "gauge",
   "description": "Power actually consumed by all devices and appliances in household.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "-P3",
     "measurement": "p1",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       { "params": [ "GAS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water",
   "type": "gauge",
   "description": "Power actually consumed by all devices and appliances in household.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "-P3",
     "measurement": "watermeter",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       { "params": [ "usages" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced this period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"AC Lifetimeproduction\")-first(\"AC Lifetimeproduction\") FROM \"solar\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power usage or delivery",
   "type": "stat",
   "description": "Power used from solar company, or power delivered to solar company. (When we generate more solar power than we can consume the number will be negative)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "total",
     "measurement": "p1",
     "query": "SELECT last(\"CURRENT_ELECTRICITY_USAGE\")*1000  - last(\"CURRENT_ELECTRICITY_DELIVERY\")*1000 FROM \"p1\" ",
     "select": [
      [
       { "params": [ "ELECTRICITY" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasstand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "GAS_READING" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "watermeter",
     "select": [
      [
       { "params": [ "current_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak solar",
   "type": "stat",
   "description": "Peak solar power during this period",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "solar",
     "query": "SELECT mean(\"AC Current 1 (A)\") FROM \"solar\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC Watts (W)" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Totaal stroom verbruik en levering",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Afgenomen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Opgewekt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "ACTUAL_ELECTRICITY_POWER_RECEIVED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stroom opgewekt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "AC 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT mean(\"AC Current 1 (A)\") FROM \"solar\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AC Current 1 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AC  2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar",
     "select": [
      [
       { "params": [ "AC Current 2 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "AC  3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solar",
     "select": [
      [
       { "params": [ "AC Current 3 (A)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deze periode",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Stroom verbruik" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ACTUAL_ELECTRICITY_POWER_RECEIVED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Stroom teruglevering" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_CONSUMED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Stroom verbruik" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ACTUAL_ELECTRICITY_POWER_RECEIVED"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Stroom teruglevering" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}