{
 "title": "Live power usage",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Power per group",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "G[[tag_Meter id]]",
     "groupBy": [
      { "params": [ "Meter id" ], "type": "tag" }
     ],
     "measurement": "Meter values",
     "select": [
      [
       { "params": [ "p1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced this period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"AC Lifetimeproduction\")-first(\"AC Lifetimeproduction\") FROM \"SolarEdge\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar power generating",
   "type": "gauge",
   "description": "Generated by solar panels.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "total",
     "measurement": "SolarEdge",
     "query": "SELECT last(\"AC Power output\") FROM \"SolarEdge\" ",
     "select": [
      [
       { "params": [ "AC Power output" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar power generated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SolarEdge",
     "query": "SELECT mean(\"AC Power output\") FROM \"SolarEdge\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "AC Power output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"AC Power output\",99.9) FROM \"SolarEdge\" WHERE $timeFilter fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power consuming",
   "type": "gauge",
   "description": "Power actually consumed by all devices and appliances in household.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "Meter id" ], "type": "tag" }
     ],
     "measurement": "Meter values",
     "query": "select sum(last) from (SELECT last(\"P1\")  FROM \"Meter values\"  GROUP BY \"Meter id\")",
     "select": [
      [
       { "params": [ "p1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power usage or delivery",
   "type": "stat",
   "description": "Power used from energy company, or power delivered to energy company. (When we generate more solar power than we can consume the number will be negative)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "total",
     "measurement": "p1",
     "query": "SELECT last(\"CURRENT_ELECTRICITY_USAGE\")*1000  - last(\"CURRENT_ELECTRICITY_DELIVERY\")*1000 FROM \"p1\" ",
     "select": [
      [
       { "params": [ "CURRENT_ELECTRICITY_USAGE" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total power usage or delivery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Using",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1",
     "query": "SELECT -mean(\"CURRENT_ELECTRICITY_USAGE\") FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "CURRENT_ELECTRICITY_USAGE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Delivering",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1",
     "query": "SELECT mean(\"CURRENT_ELECTRICITY_DELIVERY\") FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "CURRENT_ELECTRICITY_DELIVERY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak solar",
   "type": "stat",
   "description": "Peak solar power during this period",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"AC Power output\",99.9) FROM \"SolarEdge\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage per phase",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "L1",
     "measurement": "p1",
     "query": "SELECT last(\"INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE\") * 1000 - last(\"INSTANTANEOUS_ACTIVE_POWER_L1_NEGATIVE\") * 1000 FROM \"p1\" ",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "measurement": "p1",
     "query": "SELECT last(\"INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE\") * 1000 - last(\"INSTANTANEOUS_ACTIVE_POWER_L2_NEGATIVE\") * 1000  FROM \"p1\" ",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "measurement": "p1",
     "query": "SELECT last(\"INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE\") * 1000 - last(\"INSTANTANEOUS_ACTIVE_POWER_L3_NEGATIVE\") * 1000 FROM \"p1\" ",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power average per group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "G[[tag_Meter id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Meter id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Meter values",
     "query": "SELECT mean(\"P1\") FROM \"Meter values\" WHERE $timeFilter GROUP BY time($__interval), \"Meter id\" fill(null)",
     "select": [
      [
       { "params": [ "p1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "This period",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 27 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "query": "SELECT max(\"INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE\") * 1000  FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "query": "SELECT max(\"INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE\") * 1000 FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "query": "SELECT max(\"INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE\") * 1000 FROM \"p1\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power average per phase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       {
        "params": [
         "INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 32 },
   "targets": [
    {
     "alias": "L1 sag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SAG_L1_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L2 sag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SAG_L2_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L3 sag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SAG_L2_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L1 swell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SWELL_L1_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L2 swell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SWELL_L2_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L3 swell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "VOLTAGE_SWELL_L3_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Power failures",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p1",
     "select": [
      [
       { "params": [ "LONG_POWER_FAILURE_COUNT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}