--- 
- name: create /var/docker-compose/fragments
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/fragments"

- name: get keys
  set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"
    ip_address: "{{lookup('file', '/home/pi/ip') }}"

- name: Create Docker files from template
  template:
    src: "docker-compose-graphite.yaml.j2"
    dest: "/var/docker-compose/fragments/docker-compose-graphite.yaml"
    mode: 0755
    owner: pi
    group: pi
