--- 
- set_fact:
    cmdline_txt_path: /boot/cmdline.txt

- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: memory
    update: false
    # will add the argument if the key-value-pair doesn't exist

- name: cmdline.yml update cgroup_enable
  include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: cpuset
    update: false

- name: cmdline.yml update cgroup_memory
  include_tasks: cmdline.yml
  vars:
    key: cgroup_memory
    value: 1
    update: true
  register: cmdline

- name: Reboot
  shell: reboot
  when: cmdline.changed

- name: create /var/docker-compose/mqtt 
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/data/zigbee"

- name: Template zigbee files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "configuration.yaml.j2",         dest: "/var/docker-compose/data/zigbee/configuration.yaml" }

- name: add to docker-compose
  include_tasks: docker-compose.yaml
