--- 
- name: create /var/docker-compose/alertmanager 
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/alertmanager"

- name: Template alertmanager files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: "{|"
    variable_end_string: "|}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "config.yml.j2",           dest: "/var/docker-compose/data/alertmanager/config.yml" }
  
- name: get_facts
  include_tasks: get_facts.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml
