---
- name: get keys
  set_fact:
    slack_webhook: "{{lookup('file', '/home/pi/slack.webhook') }}"
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"
    ip_address: "{{lookup('file', '/home/pi/ip') }}"
    ext_ip: "{{lookup('file', '/home/pi/ext_ip') }}"
    dropbox_access_token: "{{lookup('file', '/home/pi/dropbox_access_token') }}"