--- 
- name: get facts
  include_tasks: get_facts.yaml

- name: create /var/docker-compose/data/rclone/
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/rclone/config/"
  - "/var/docker-compose/data/rclone/logs/"

- name: Template alertmanager files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "rclone.conf.j2", dest: "/var/docker-compose/data/rclone/config/rclone.conf" }
  
- name: add to docker-compose
  include_tasks: docker-compose.yaml

- name: Recursively remove files /var/docker-compose/prometheus
  ansible.builtin.file:
    path: "{{ items }}"
    state: absent  
  with_items:         
  - "/var/docker-compose/prometheus.links"
  - "/var/docker-compose/prometheus.targets"