--- 
- name: create /var/docker-compose/data/backup/{{ ip_address }}
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/backup/{{ ip_address }}"

- name: get keys
  set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"
    ip_address: "{{lookup('file', '/home/pi/ip') }}"

- name: set source prometheus
  include_tasks: prometheus.yaml
  
- name: add to docker-compose
  include_tasks: docker-compose.yaml
