--- 
- name: create /var/docker-compose/mqtt 
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/grafana/data"
  - "/var/docker-compose/data/grafana/dashboards"
  - "/var/docker-compose/data/grafana/env"
    

- name: Add the user 'grafana' to a specific uid and a primary group of 'pi'
  user:
    name: grafana
    comment: grafana
    uid: 472
#    group: pi
    groups: pi,dialout

- name: copy env files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "files/env/env.grafana", dest: "/var/docker-compose/grafana/env/env.grafana" }

- name: copy Grafana dashboards files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-compose/data/grafana/dashboards/"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/dashboards/*"
  
- name: add to docker-compose
  include_tasks: docker-compose.yaml
