--- 
- name: create /var/docker-compose/grafana 
  file:
    path: "{{  item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/grafana/data"
  - "/var/docker-compose/data/grafana/dashboards"
  - "/var/docker-compose/data/grafana/env"
    

- name: Add the user 'grafana' to a specific uid and a primary group of 'pi'
  user:
    name: grafana
    comment: grafana
    uid: 472
#    group: pi
    groups: pi,dialout

- name: copy Docker Compose env files
  copy:
    src: "{{ item }}"
    dest: "/var/docker-compose/data/grafana/env"
    mode: 0755
    owner: pi
    group: pi
  with_fileglob:
    - "files/env/*"

#- name: copy env files
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    mode: 0755
#    owner: pi
#    group: pi
#  with_items:
#  - { src: "files/env/env.grafana", dest: "/var/docker-compose/grafana/env/env.grafana" }
 
- name: get_facts
  include_tasks: ../../../tasks/get_facts.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml
