--- 
- name: create /var/docker-compose/data/nginx/templates
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/nginx/templates"

- name: get keys
  set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"
    ip_address: "{{lookup('file', '/home/pi/ip') }}"

- name: Template nginx files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "default.j2", dest: "/var/docker-compose/data/nginx/templates/default.j2" }

- name: add to docker-compose
  include_tasks: docker-compose.yaml
