---
- name: Check for docker in /run
  stat:
    path: /run/docker
  register: p

- name: Install Docker
  shell:
    cmd: "curl -sSL https://get.docker.com | sh"
  when: not p.stat.exists

- name: Add the user 'pi' with a bash shell, appending the group 'docker' to the user's groups
  user:
    name: pi
    shell: /bin/bash
    groups: 
    - docker
    append: yes

- name: install libffi-dev libssl-dev
  apt:
    name: [ "libffi-dev", "libssl-dev" ]
    install_recommends: yes

- name: install python3
  apt:
    name: [ "python3","python3-pip" ]
    install_recommends: yes

- name: install python-configparser
  apt:
    name: [ "python-configparser" ]
    state: absent

#  shell:
#    cmd: "pip3 -v install docker-compose"    

- name: Install docker-compose
  pip:
    name: docker-compose

- name: create /var/docker-compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    #owner: postgres
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/data/portainer"    

- name: get keys
  set_fact:
    ip_address: "{{lookup('file', '/home/pi/ip') }}"
  
#portainer/portainer:linux-arm
- name: Create portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce    
    container_default_behavior: no_defaults
    state: present
    recreate: yes
    env:
      admin-password-file: "{{ pswrdfile }}"
      host: "{{ ip_address }}"
    ports: 
      - "80:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /data/portainer_data:/data 