---
- name: create /var/docker-compose/prometheus
  file:
    path: "{{  item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - "/var/docker-compose/data/prometheus/config"
  - "/var/docker-compose/data/prometheus/data"

- name: set source prometheus
  include_tasks: prometheus.yaml

- name: get prometheus links and targets
  set_fact:
    var_targets: "{{lookup('file', '/var/docker-compose/prometheus.targets') }}"
    var_links: "{{lookup('file', '/var/docker-compose/prometheus.links') }}"
   
- name: copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "rules.yml",  dest: "/var/docker-compose/data/prometheus/config/rules.yml" }

- name: Template prometheus files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "prometheus.yml.j2",  dest: "/var/docker-compose/data/prometheus/config/prometheus.yml" }

- name: get_facts
  include_tasks: ../../../tasks/get_facts.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml

- name: Remove files /var/docker-compose/prometheus
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent  
  with_items:         
  - "/var/docker-compose/prometheus.links"
  - "/var/docker-compose/prometheus.targets"

- name: remove reboot file prometheus
  shell:
    cmd: "rm -rf '/var/docker-compose/data/prometheus/data/wal'"
  ignore_errors: True
