---
- name: create /var/docker-compose/mqtt
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - "/var/docker-compose/data/prometheus/config"
  - "/var/docker-compose/data/prometheus/data"

- name: get targets
  command: 'cat /var/docker-compose/prometheus | sed -e "s/$/\\", /" | sed -e "s/^/\\"/" | tr -d" " "\n" '
  register: command_output1

- name: get links
  command: "cat /var/docker-compose/prometheus | cut -d':' -f1  | sed -e 's/^/      - /' | sed 's /(.*/) /1:/1 '"
  register: command_output2


- set_fact:
    var_targets: "{{ command_output1.stdout }}"

- set_fact:
    var_links: "{{ command_output2.stdout }}"

- name: copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "rules.yml",  dest: "/var/docker-compose/data/prometheus/config/rules.yml" }

- name: Template prometheus files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "prometheus.yml.j2",  dest: "/var/docker-compose/data/prometheus/config/prometheus.yml" }

- name: set source prometheus
  include_tasks: prometheus.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml
