---
- name: Add a line to prometheus file
  ansible.builtin.lineinfile:
    path: /var/docker-compose/prometheus.targets
    line: '"{{ containter_name }}:{{ containter_expose_port }}",'
    create: yes
