--- 
- set_fact:
    cmdline_txt_path: /boot/cmdline.txt

- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: memory
    update: false
    # will add the argument if the key-value-pair doesn't exist

- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: cpu
    update: false

- include_tasks: cmdline.yml
  vars:
    key: cgroup_memory
    value: 1
    update: true

#- name: Add an apt key by id from a keyserver
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 04EE7237B7D453EC
#
#- name: Add an apt key by id from a keyserver
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 648ACFD622F3D138

#- name: Add buster-backports to /etc/apt/sources.list
#  lineinfile:
#    path: /etc/apt/sources.list
#    line: deb http://deb.debian.org/debian buster-backports main    

#- name: apt-get update
#  shell:
#    cmd: "apt-get update"

#- name: apt-get install libseccomp2/buster-backports
#  shell:
#    cmd: "apt install libseccomp2/buster-backports"    

- name: create /var/docker-compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    #owner: postgres
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/data/mqtt/config"    
    - "/var/docker-compose/data/mqtt/data"
    - "/var/docker-compose/data/mqtt/log"
    - "/var/docker-compose/data/zigbee"

- name: add group
  shell:
    cmd: "usermod -aG dialout $(whoami)"
 
- name: copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "files/data/mqtt/config/mosquitto.conf", dest: "/var/docker-compose/data/mqtt/config/mosquitto.conf" }
  - { src: "files/data/mqtt/config/passwords.mqtt", dest: "/var/docker-compose/data/mqtt/config/passwords.mqtt" }
  
- name: get keys
  set_fact:
    pi_password: "{{lookup('file', '{{ pswrdfile }}') }}"
    ip_address: "{{lookup('file', '/home/pi/ip') }}"

- name: Create Docker files from template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "template/docker-compose.yml.j2",                  dest: "/var/docker-compose/docker-compose.yml" }    
  - { src: "files/data/zigbee/configuration.yaml.j2",         dest: "/var/docker-compose/data/zigbee/configuration.yaml" }

- name: deploy Docker Compose stack (first time takes a lot of time, hour or more)
  shell:
    cmd: "docker-compose up -d --force-recreate --remove-orphans"
  args:
    chdir:  /var/docker-compose
  